name: pixel_scan
description: "Pixel Scan Test Project"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.6
  provider: ^6.1.5
  flutter_svg: ^2.1.0
  localization: ^2.1.1
  go_router: ^15.1.3
  cunning_document_scanner: ^1.2.3
  pro_image_editor: ^9.11.2
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1
  smooth_page_indicator: ^1.2.1
  printing: ^5.14.2
  share_plus: ^11.0.0
  pdf: ^3.11.3
  path_provider: ^2.1.5
  flutter_screenutil: ^5.9.3
  in_app_review: ^2.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - lib/i18n/
